name: Python Package CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2025]
        python-version: ['3.11', '3.12']

    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Set up Python and PDM cache
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pdm'

    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pipx
        pipx install pdm
      shell: bash

    - name: Dump environment details
      run: |
        echo "OS/Runner: ${{ runner.os }}"
        echo "Python version:"
        python --version
        echo "PDM version:"
        pdm --version
        echo "PDM Environment Info:"
        pdm info
        echo "PATH:"
        echo $PATH
      shell: bash

    - name: Install dependencies
      run: pdm install -vv --group dev

    - name: Verify Dependency Tree
      run: pdm show --tree

    - name: Run Unit Tests
      run: pdm run pytest -vv -m "not integration" --cov=./ --cov-report=xml:coverage-unit.xml

    - name: Run Integration Tests
      run: pdm run pytest -vv -m "integration" --cov=./ --cov-report=xml:coverage-integration.xml

    - name: Upload Unit Test coverage to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage-unit.xml
        flags: ${{ matrix.os }}-py${{ matrix.python-version }}-unit
        fail_ci_if_error: true
        verbose: true

    - name: Upload Integration Test coverage to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage-integration.xml
        flags: ${{ matrix.os }}-py${{ matrix.python-version }}-integration
        fail_ci_if_error: true
        verbose: true

    - name: Upload reports and logs on failure
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      if: failure()
      with:
        name: ci-failure-reports-${{ matrix.os }}-${{ matrix.python-version }}
        path: |
          coverage-unit.xml
          coverage-integration.xml