name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.12'

      - name: Run pre-commit checks
        uses: pre-commit/action@2c7b3805553e5491e3b089151c0d75a828c531a6 # v3.0.1

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pdm'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install dependencies
        run: pdm install -d -v

      - name: Dump environment info (for debugging)
        run: pdm info

      - name: Run Unit Tests with Coverage
        run: pdm run pytest tests/unit --cov=src --cov-report=xml:coverage-unit.xml

      - name: Run Integration Tests with Coverage
        run: pdm run pytest tests/integration --cov=src --cov-append --cov-report=xml:coverage-integration.xml

      - name: Upload Unit Test Coverage to Codecov
        uses: codecov/codecov-action@3642b8761a27e77b6399c4146c875f508003f412 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage-unit.xml
          flags: ${{ matrix.os }}-py${{ matrix.python-version }}-unit
          fail_ci_if_error: true
          verbose: true

      - name: Upload Integration Test Coverage to Codecov
        uses: codecov/codecov-action@3642b8761a27e77b6399c4146c875f508003f412 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage-integration.xml
          flags: ${{ matrix.os }}-py${{ matrix.python-version }}-integration
          fail_ci_if_error: true
          verbose: true

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@af59e669b552399c27940173e44a2c9183490333 # v4.4.0
        with:
          name: test-logs-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            coverage-unit.xml
            coverage-integration.xml